spring:
  profiles:
    active: local

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  secret: ${jwt.secret}
  access-token-exp-seconds: ${jwt.access-token-exp-seconds}
  refresh-token-exp-seconds: ${jwt.refresh-token-exp-seconds}

file:
  size: ${image.size}
  upload.dir: ${file.upload.dir}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
      group:
        readiness:
          include: readinessState, db
  endpoints:
    web:
      exposure:
        include: health,info,Prometheus
  health:
    db:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

server:
  tomcat:
    reregistration:
      enabled: true